export enum EnvVar {
  NODE_ENV = 'NODE_ENV',
  PORT = 'PORT',
  DATABASE = 'DATABASE',
  DATABASE_NAME = 'DATABASE_NAME',
  DATABASE_PORT = 'DATABASE_PORT',
  DATABASE_HOST = 'DATABASE_HOST',
  DATABASE_USERNAME = 'DATABASE_USERNAME',
  DATABASE_PASSWORD = 'DATABASE_PASSWORD',

  JWT_SECRET = 'JWT_SECRET',
}

export type TEnvVar = Record<keyof typeof EnvVar, string>;
