version: '3.9'

services:
  db:
    container_name: store-db
    image: postgres:13.3
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: store-db
    ports:
      - '5432:5432'